Add workaround for Debian #855999

diff --git a/test_pkgs b/test_pkgs
--- a/test_pkgs
+++ b/test_pkgs
@@ -177,15 +177,32 @@ for p in $@; do
     error "no .dsc file in package $p"
   fi
 
+  # Run job
+
   mkdir $ODIR/$p
 
-  # TODO: use '--timeout 1h' when https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=855999 is fixed
-  if ! nice sudo $PBUILDER --build --configfile pbuilderrc --hookdir pbuilder-hooks --bindmounts $SHARED_DIR src/*.dsc 2>&1 | tee $ODIR/$p/stdout_stderr.txt; then
+  start_time=$(date +'%F %T')
+
+  ( nice sudo $PBUILDER --timeout 1h --build --configfile pbuilderrc --hookdir pbuilder-hooks --bindmounts $SHARED_DIR src/*.dsc >$ODIR/$p/stdout_stderr.txt 2>&1 ) &
+  BUILD_PID=$!
+
+  sleep 1
+  tail -f $ODIR/$p/stdout_stderr.txt &  # Can't use tee with --timeout (https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=855999)
+  TAIL_PID=$!
+
+  if ! wait $BUILD_PID; then
     warn "failed to build package $p"
     NFAILS=$((NFAILS + 1))
   fi
 
+  kill $TAIL_PID
+
+  # Copy additional outputs
+
+  journalctl -k -S "$start_time" > $ODIR/$p/syslog
   cp -r $SHARED_DIR/output $ODIR/$p
+
+  # Clean up
 
   rm -rf src/* $SHARED_DIR/output/*
 done
